// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: collector/collector.proto

package collectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRepoRequest) Reset() {
	*x = GetInfoRepoRequest{}
	mi := &file_collector_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRepoRequest) ProtoMessage() {}

func (x *GetInfoRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRepoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRepoRequest) Descriptor() ([]byte, []int) {
	return file_collector_collector_proto_rawDescGZIP(), []int{0}
}

func (x *GetInfoRepoRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GetInfoRepoRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type RepoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Stargazers    uint64                 `protobuf:"varint,3,opt,name=stargazers,proto3" json:"stargazers,omitempty"`
	Forks         uint64                 `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	Createdat     string                 `protobuf:"bytes,5,opt,name=createdat,proto3" json:"createdat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoInfo) Reset() {
	*x = RepoInfo{}
	mi := &file_collector_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoInfo) ProtoMessage() {}

func (x *RepoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_collector_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoInfo.ProtoReflect.Descriptor instead.
func (*RepoInfo) Descriptor() ([]byte, []int) {
	return file_collector_collector_proto_rawDescGZIP(), []int{1}
}

func (x *RepoInfo) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *RepoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RepoInfo) GetStargazers() uint64 {
	if x != nil {
		return x.Stargazers
	}
	return 0
}

func (x *RepoInfo) GetForks() uint64 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *RepoInfo) GetCreatedat() string {
	if x != nil {
		return x.Createdat
	}
	return ""
}

type GetInfoRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repoinfo      *RepoInfo              `protobuf:"bytes,1,opt,name=repoinfo,proto3" json:"repoinfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRepoResponse) Reset() {
	*x = GetInfoRepoResponse{}
	mi := &file_collector_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRepoResponse) ProtoMessage() {}

func (x *GetInfoRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRepoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoRepoResponse) Descriptor() ([]byte, []int) {
	return file_collector_collector_proto_rawDescGZIP(), []int{2}
}

func (x *GetInfoRepoResponse) GetRepoinfo() *RepoInfo {
	if x != nil {
		return x.Repoinfo
	}
	return nil
}

type GetInfoRepositoriesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Repositoriesinfo []*RepoInfo            `protobuf:"bytes,1,rep,name=repositoriesinfo,proto3" json:"repositoriesinfo,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetInfoRepositoriesResponse) Reset() {
	*x = GetInfoRepositoriesResponse{}
	mi := &file_collector_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRepositoriesResponse) ProtoMessage() {}

func (x *GetInfoRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*GetInfoRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_collector_collector_proto_rawDescGZIP(), []int{3}
}

func (x *GetInfoRepositoriesResponse) GetRepositoriesinfo() []*RepoInfo {
	if x != nil {
		return x.Repositoriesinfo
	}
	return nil
}

var File_collector_collector_proto protoreflect.FileDescriptor

const file_collector_collector_proto_rawDesc = "" +
	"\n" +
	"\x19collector/collector.proto\x12\x0fproto.collector\x1a\x1bgoogle/protobuf/empty.proto\">\n" +
	"\x12GetInfoRepoRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\"\x9c\x01\n" +
	"\bRepoInfo\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"stargazers\x18\x03 \x01(\x04R\n" +
	"stargazers\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x04R\x05forks\x12\x1c\n" +
	"\tcreatedat\x18\x05 \x01(\tR\tcreatedat\"L\n" +
	"\x13GetInfoRepoResponse\x125\n" +
	"\brepoinfo\x18\x01 \x01(\v2\x19.proto.collector.RepoInfoR\brepoinfo\"d\n" +
	"\x1bGetInfoRepositoriesResponse\x12E\n" +
	"\x10repositoriesinfo\x18\x01 \x03(\v2\x19.proto.collector.RepoInfoR\x10repositoriesinfo2\xc2\x01\n" +
	"\tCollector\x12X\n" +
	"\vGetInfoRepo\x12#.proto.collector.GetInfoRepoRequest\x1a$.proto.collector.GetInfoRepoResponse\x12[\n" +
	"\x13GetInfoRepositories\x12\x16.google.protobuf.Empty\x1a,.proto.collector.GetInfoRepositoriesResponseB\xa9\x01\n" +
	"\x13com.proto.collectorB\x0eCollectorProtoP\x01Z%repo-stat/proto/collector;collectorpb\xa2\x02\x03PCX\xaa\x02\x0fProto.Collector\xca\x02\x0fProto\\Collector\xe2\x02\x1bProto\\Collector\\GPBMetadata\xea\x02\x10Proto::Collectorb\x06proto3"

var (
	file_collector_collector_proto_rawDescOnce sync.Once
	file_collector_collector_proto_rawDescData []byte
)

func file_collector_collector_proto_rawDescGZIP() []byte {
	file_collector_collector_proto_rawDescOnce.Do(func() {
		file_collector_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collector_collector_proto_rawDesc), len(file_collector_collector_proto_rawDesc)))
	})
	return file_collector_collector_proto_rawDescData
}

var file_collector_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_collector_collector_proto_goTypes = []any{
	(*GetInfoRepoRequest)(nil),          // 0: proto.collector.GetInfoRepoRequest
	(*RepoInfo)(nil),                    // 1: proto.collector.RepoInfo
	(*GetInfoRepoResponse)(nil),         // 2: proto.collector.GetInfoRepoResponse
	(*GetInfoRepositoriesResponse)(nil), // 3: proto.collector.GetInfoRepositoriesResponse
	(*emptypb.Empty)(nil),               // 4: google.protobuf.Empty
}
var file_collector_collector_proto_depIdxs = []int32{
	1, // 0: proto.collector.GetInfoRepoResponse.repoinfo:type_name -> proto.collector.RepoInfo
	1, // 1: proto.collector.GetInfoRepositoriesResponse.repositoriesinfo:type_name -> proto.collector.RepoInfo
	0, // 2: proto.collector.Collector.GetInfoRepo:input_type -> proto.collector.GetInfoRepoRequest
	4, // 3: proto.collector.Collector.GetInfoRepositories:input_type -> google.protobuf.Empty
	2, // 4: proto.collector.Collector.GetInfoRepo:output_type -> proto.collector.GetInfoRepoResponse
	3, // 5: proto.collector.Collector.GetInfoRepositories:output_type -> proto.collector.GetInfoRepositoriesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_collector_collector_proto_init() }
func file_collector_collector_proto_init() {
	if File_collector_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collector_collector_proto_rawDesc), len(file_collector_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_collector_proto_goTypes,
		DependencyIndexes: file_collector_collector_proto_depIdxs,
		MessageInfos:      file_collector_collector_proto_msgTypes,
	}.Build()
	File_collector_collector_proto = out.File
	file_collector_collector_proto_goTypes = nil
	file_collector_collector_proto_depIdxs = nil
}
