// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: subscriber/subscriber.proto

package subscriberv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_subscriber_subscriber_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriber_subscriber_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_subscriber_subscriber_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_subscriber_subscriber_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscriber_subscriber_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_subscriber_subscriber_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoName      string                 `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	OwnerName     string                 `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscriber_subscriber_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscriber_subscriber_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscriber_subscriber_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *Subscription) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Subscription) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsResponse) Reset() {
	*x = GetSubscriptionsResponse{}
	mi := &file_subscriber_subscriber_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsResponse) ProtoMessage() {}

func (x *GetSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscriber_subscriber_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_subscriber_subscriber_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type DeleteSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoName      string                 `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	OwnerName     string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_subscriber_subscriber_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriber_subscriber_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscriber_subscriber_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSubscriptionRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *DeleteSubscriptionRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoName      string                 `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	OwnerName     string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_subscriber_subscriber_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriber_subscriber_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscriber_subscriber_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSubscriptionRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

var File_subscriber_subscriber_proto protoreflect.FileDescriptor

const file_subscriber_subscriber_proto_rawDesc = "" +
	"\n" +
	"\x1bsubscriber/subscriber.proto\x12\rsubscriber.v1\x1a\x1bgoogle/protobuf/empty.proto\"\r\n" +
	"\vPingRequest\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"y\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_name\x18\x02 \x01(\tR\brepoName\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x03 \x01(\tR\townerName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"]\n" +
	"\x18GetSubscriptionsResponse\x12A\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1b.subscriber.v1.SubscriptionR\rsubscriptions\"W\n" +
	"\x19DeleteSubscriptionRequest\x12\x1b\n" +
	"\trepo_name\x18\x01 \x01(\tR\brepoName\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\"W\n" +
	"\x19CreateSubscriptionRequest\x12\x1b\n" +
	"\trepo_name\x18\x01 \x01(\tR\brepoName\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName2\xd2\x02\n" +
	"\n" +
	"Subscriber\x12?\n" +
	"\x04Ping\x12\x1a.subscriber.v1.PingRequest\x1a\x1b.subscriber.v1.PingResponse\x12S\n" +
	"\x10GetSubscriptions\x12\x16.google.protobuf.Empty\x1a'.subscriber.v1.GetSubscriptionsResponse\x12V\n" +
	"\x12DeleteSubscription\x12(.subscriber.v1.DeleteSubscriptionRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x12CreateSubscription\x12(.subscriber.v1.CreateSubscriptionRequest\x1a\x16.google.protobuf.EmptyB\xb3\x01\n" +
	"\x11com.subscriber.v1B\x0fSubscriberProtoP\x01Z8yadro.com/course/proto/gen/go/subscriber/v1;subscriberv1\xa2\x02\x03SXX\xaa\x02\rSubscriber.V1\xca\x02\rSubscriber\\V1\xe2\x02\x19Subscriber\\V1\\GPBMetadata\xea\x02\x0eSubscriber::V1b\x06proto3"

var (
	file_subscriber_subscriber_proto_rawDescOnce sync.Once
	file_subscriber_subscriber_proto_rawDescData []byte
)

func file_subscriber_subscriber_proto_rawDescGZIP() []byte {
	file_subscriber_subscriber_proto_rawDescOnce.Do(func() {
		file_subscriber_subscriber_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscriber_subscriber_proto_rawDesc), len(file_subscriber_subscriber_proto_rawDesc)))
	})
	return file_subscriber_subscriber_proto_rawDescData
}

var file_subscriber_subscriber_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_subscriber_subscriber_proto_goTypes = []any{
	(*PingRequest)(nil),               // 0: subscriber.v1.PingRequest
	(*PingResponse)(nil),              // 1: subscriber.v1.PingResponse
	(*Subscription)(nil),              // 2: subscriber.v1.Subscription
	(*GetSubscriptionsResponse)(nil),  // 3: subscriber.v1.GetSubscriptionsResponse
	(*DeleteSubscriptionRequest)(nil), // 4: subscriber.v1.DeleteSubscriptionRequest
	(*CreateSubscriptionRequest)(nil), // 5: subscriber.v1.CreateSubscriptionRequest
	(*emptypb.Empty)(nil),             // 6: google.protobuf.Empty
}
var file_subscriber_subscriber_proto_depIdxs = []int32{
	2, // 0: subscriber.v1.GetSubscriptionsResponse.subscriptions:type_name -> subscriber.v1.Subscription
	0, // 1: subscriber.v1.Subscriber.Ping:input_type -> subscriber.v1.PingRequest
	6, // 2: subscriber.v1.Subscriber.GetSubscriptions:input_type -> google.protobuf.Empty
	4, // 3: subscriber.v1.Subscriber.DeleteSubscription:input_type -> subscriber.v1.DeleteSubscriptionRequest
	5, // 4: subscriber.v1.Subscriber.CreateSubscription:input_type -> subscriber.v1.CreateSubscriptionRequest
	1, // 5: subscriber.v1.Subscriber.Ping:output_type -> subscriber.v1.PingResponse
	3, // 6: subscriber.v1.Subscriber.GetSubscriptions:output_type -> subscriber.v1.GetSubscriptionsResponse
	6, // 7: subscriber.v1.Subscriber.DeleteSubscription:output_type -> google.protobuf.Empty
	6, // 8: subscriber.v1.Subscriber.CreateSubscription:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_subscriber_subscriber_proto_init() }
func file_subscriber_subscriber_proto_init() {
	if File_subscriber_subscriber_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscriber_subscriber_proto_rawDesc), len(file_subscriber_subscriber_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscriber_subscriber_proto_goTypes,
		DependencyIndexes: file_subscriber_subscriber_proto_depIdxs,
		MessageInfos:      file_subscriber_subscriber_proto_msgTypes,
	}.Build()
	File_subscriber_subscriber_proto = out.File
	file_subscriber_subscriber_proto_goTypes = nil
	file_subscriber_subscriber_proto_depIdxs = nil
}
